name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - uses: actions/checkout@v5
      - name: go.lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 120s --max-same-issues 50
