name: Go

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: go.setup
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: go.build
      run: go build -v ./...

    - name: go.test
      run: |
        go test -v -coverprofile=cover.out -covermode=atomic ./...
        go tool cover -html=cover.out -o cover.html

    - name: go.test.coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./cover.out
        flags: unittests
        verbose: true
